app = "pumpfun-worker-bot"
primary_region = "fra"
kill_signal = "SIGINT"
kill_timeout = "30s"

[build]

[env]
  NODE_ENV = "production"

[[mounts]]
  source = "bot_state"
  destination = "/data"

[processes]
  app = "npm start"

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
